name: core-build
on:
  push:
  pull_request:

jobs:
  build:
    uses: AzerothLegacy/test-workflows/.github/workflows/core_build_modules.yml@main
    with:
      module_repo: ${{ github.event.repository.name }}